@ECHO OFF
REM  File: INST.BAT BY Yi-Wan LIN 2001/10/3 04:48PM
REM  NOTE:1.RUN THIS BATCH FILE UNDER A:\
REM       2.The SFX files are made of ARJ V2.50a

REM initial variable of environment
SET INSTSOURCEDIR=.
SET INSTDIR=INSTTMP
SET D2EXIST=
SET BEXIST=
SET PRE_PATH=%PATH%
SET MIN_SIZE=8000000
SET FINISHED=
SET PATH=C:\;C:\DOS;C:\TOOLS;C:\MLC;C:\NET;C:\%INSTDIR%;
SET INSTVERBAT=INSTVER.BAT

IF NOT "%1"=="" SET INSTSOURCEDIR=%1

REM 400i Series not install to D:
IF "%PRODUCTNAME%"=="LNC-M400I"  GOTO D2L2
IF "%PRODUCTNAME%"=="LNC-T400I"  GOTO D2L2
IF "%PRODUCTNAME%"=="LNC-M400i"  GOTO D2L2
IF "%PRODUCTNAME%"=="LNC-T400i"  GOTO D2L2
IF "%PRODUCTNAME%"=="Lnc-M400i"  GOTO D2L2
IF "%PRODUCTNAME%"=="Lnc-T400i"  GOTO D2L2
IF "%PRODUCTNAME%"=="lnc-m400i"  GOTO D2L2
IF "%PRODUCTNAME%"=="lnc-t400i"  GOTO D2L2

if "%USBDISK%"=="D:" goto D2L2
%INSTSOURCEDIR%\isdsk.exe D:\
IF ERRORLEVEL 2 GOTO D2L2
IF ERRORLEVEL 1 GOTO D2L1
GOTO D2L2
:D2L1
SET D2EXIST=YES
:D2L2

%INSTSOURCEDIR%\isdsk.exe B:\
IF ERRORLEVEL 3 GOTO BL3
IF ERRORLEVEL 2 GOTO BL2
GOTO BL3
:BL2
SET BEXIST=YES
:BL3

IF "%INSTSOURCEDIR%"=="C:\%INSTDIR%" GOTO N0EXTINST
IF EXIST C:\%INSTDIR%\*.*  deltree /Y C:\%INSTDIR%  >NUL
md C:\%INSTDIR%          >NUL
md C:\%INSTDIR%\MACHINE  >NUL
md C:\%INSTDIR%\Maker    >NUL
md C:\%INSTDIR%\Ncfiles  >NUL
md C:\%INSTDIR%\Cam      >NUL
:N0EXTINST

cls
%INSTSOURCEDIR%\diskfree.exe C %MIN_SIZE%
IF ERRORLEVEL 5 GOTO D1_ENOUGH
ECHO [CF 1]
PAUSE
GOTO QUIT
:D1_ENOUGH

IF "%D2EXIST%"==""  GOTO D2_ENOUGH
cls
%INSTSOURCEDIR%\diskfree.exe D %MIN_SIZE%
IF ERRORLEVEL 5 GOTO D2_ENOUGH
ECHO [CF 2]
PAUSE
GOTO QUIT
:D2_ENOUGH

IF "%INSTSOURCEDIR%"=="C:\%INSTDIR%" GOTO N1EXTINST
copy /y %INSTSOURCEDIR%\%INSTVERBAT% C:\%INSTDIR%\.  >NUL
:N1EXTINST
copy /y %INSTSOURCEDIR%\isdsk.exe    C:\DOS\.        >NUL
CALL C:\%INSTDIR%\%INSTVERBAT%
IF EXIST C:\%ROOT%\EXE\%INSTVERBAT%  CALL C:\%ROOT%\EXE\%INSTVERBAT%
IF "%LNCVER%"=="" SET LNCVER=Not install

REM ------------------------------------------------------------------
cls
ECHO  ======================================
ECHO  WELCOME TO INSTALL %PRODUCTNAME% SERIES
ECHO  ======================================
ECHO  Current Version:
ECHO     %LNCVER%
ECHO.
ECHO  Installing Version:
ECHO     %LNC_VERSION%
ECHO.
choice /n /c:y1n0 Are you sure to install[1:Y,0:N]?
IF ERRORLEVEL 3 GOTO QUIT

REM ----------Full Install ----------------------------------------------------
REM === copy install files to install dir of c disk ===
cls
ECHO.
ECHO Installing...
ECHO Please wait,file preparing ...
ECHO.
IF "%INSTSOURCEDIR%"=="C:\%INSTDIR%" GOTO N2EXTINST
COPY /V /Y %INSTSOURCEDIR%\MACHINE\*.*  C:\%INSTDIR%\MACHINE  >NUL
IF EXIST %INSTSOURCEDIR%\Maker\*.*    COPY /V /Y %INSTSOURCEDIR%\Maker\*.*    C:\%INSTDIR%\Maker   >NUL
IF EXIST %INSTSOURCEDIR%\Ncfiles\*.*  COPY /V /Y %INSTSOURCEDIR%\Ncfiles\*.*  C:\%INSTDIR%\Ncfiles  >NUL
IF EXIST %INSTSOURCEDIR%\Cam\*.*      COPY /V /Y %INSTSOURCEDIR%\Cam\*.*      C:\%INSTDIR%\Cam   >NUL
COPY /V /Y %INSTSOURCEDIR%\%EXESFX%     C:\%INSTDIR%\.        >NUL
REM COPY /V /Y %INSTSOURCEDIR%\RES.BAT      C:\%INSTDIR%\.        >NUL
copy /V /Y %INSTSOURCEDIR%\CONFIG.SYS   C:\%INSTDIR%\.        >NUL
copy /V /Y %INSTSOURCEDIR%\AUTOEXEC.BAT C:\%INSTDIR%\.        >NUL
:N2EXTINST

IF NOT EXIST C:\%INSTDIR%\MACHINE\param.*  GOTO xInstFailure
IF NOT EXIST C:\%INSTDIR%\%EXESFX%         GOTO xInstFailure

IF NOT "%AUTOVER%"=="%AUTO_VERSION%" copy /y %INSTSOURCEDIR%\%INSTVERBAT% C:\UpDate.txt >NUL
IF NOT "%AUTOVER%"=="%AUTO_VERSION%" GOTO BAT_START
IF EXIST C:\%ROOT%\EXE\RUN286.EXE GOTO NOT_COPY_BOOT_FILE
:BAT_START
REM backup autoexec.bat
IF EXIST C:\AUTOEXEC.BAK  DEL C:\AUTOEXEC.BAK >NUL
IF EXIST C:\AUTOEXEC.BAT  REN C:\AUTOEXEC.BAT  AUTOEXEC.BAK >NUL

REM backup CONFIG.SYS
IF EXIST C:\CONFIG.BAK  DEL C:\CONFIG.BAK >NUL
IF EXIST C:\CONFIG.SYS  REN C:\CONFIG.SYS CONFIG.BAK  >NUL

REM copy autoexec.bat and config.sys to c disk
COPY /Y /V C:\%INSTDIR%\CONFIG.SYS   C:\  >NUL
COPY /Y /V C:\%INSTDIR%\AUTOEXEC.BAT C:\  >NUL

:NOT_COPY_BOOT_FILE
IF NOT EXIST C:\%ROOT%\machine\xpnet.bat   COPY /Y /V C:\%INSTDIR%\CONFIG.SYS   C:\  >NUL
IF NOT EXIST C:\%ROOT%\machine\xpnet.bat   COPY /Y /V C:\%INSTDIR%\AUTOEXEC.BAT C:\  >NUL

REM For M515i/M516i
set DirSrc=
set DirTar=
IF "%RootOrg%" == "LNCM515I"  IF "%LNC_TYPE%" == "M516i"  set DirSrc=LncM515i
IF "%RootOrg%" == "LNCM516I"  IF "%LNC_TYPE%" == "M515i"  set DirSrc=LncM516i
IF "%DirSrc%" == "LncM515i"  set DirTar=LncM516i
IF "%DirSrc%" == "LncM516i"  set DirTar=LncM515i
if "%DirSrc%" == "" goto Next516i
  COPY /Y /V C:\%INSTDIR%\Machine\mmibase.ini C:\%DirSrc%\machine\.
  MOVE C:\%DirSrc% C:\%ROOT%
  DELTREE /y C:\%DirSrc%.B2
  MOVE C:\%ROOT%\EXE\%DirSrc%.exe C:\%ROOT%\EXE\%EXENAME%
:Next516i

REM backup present system
IF EXIST C:\%ROOT%\EXE\RUN286.EXE  IF EXIST C:\%ROOT%.BAK\EXE\RUN286.EXE  ECHO Previous Backup found!,deleting...
IF EXIST C:\%ROOT%\EXE\RUN286.EXE  IF EXIST C:\%ROOT%.BAK\EXE\RUN286.EXE  deltree /Y C:\%ROOT%.BAK  >NUL
IF EXIST C:\%ROOT%\EXE\RUN286.EXE  ATTRIB -s -h C:\%ROOT% >NUL
IF EXIST C:\%ROOT%\EXE\RUN286.EXE  MOVE C:\%ROOT% C:\%ROOT%.BAK >NUL

REM === check RamDisk is exist ===
IF "%BEXIST%"=="YES"  IF EXIST B:\PARAM.*  COPY /Y /V B:\*.* C:\%ROOT%.BAK\MACHINE  >NUL

REM ==============================
IF NOT EXIST C:\%ROOT%.BAK\EXIST.DIR  GOTO SKIP3
ECHO C:\%ROOT%.BAK >C:\%ROOT%.BAK\EXIST.DIR
:SKIP3
cls
ECHO.
ECHO Installing ...
ECHO.
IF NOT EXIST C:\%ROOT%\EXIST.DIR  md C:\%ROOT%  >NUL
ECHO C:\%ROOT% >C:\%ROOT%\EXIST.DIR
md C:\%ROOT%\MACHINE  >NUL
md C:\%ROOT%\FONTS    >NUL

REM current dir: system root
C:
cd \%ROOT%
COPY /Y /V C:\%INSTDIR%\MACHINE\*.* C:\%ROOT%\MACHINE\.  >NUL

REM===============================================================
C:\%INSTDIR%\%EXESFX% -y  >NUL
IF ERRORLEVEL 1  GOTO xCNCEXE

ECHO SET LNCVER=%LNC_VERSION%> C:\%ROOT%\EXE\%INSTVERBAT%
ECHO SET AUTOVER=%AUTO_VERSION%>> C:\%ROOT%\EXE\%INSTVERBAT%
IF EXIST C:\%ROOT%.BAK\exe\xpnet.bat   copy /y /v C:\%ROOT%.BAK\exe\xpnet.bat C:\%ROOT%\MACHINE\.   >NUL
IF EXIST C:\%ROOT%.BAK\exe\xpnet.bat   ECHO Set NETWORK=RECON>C:\%ROOT%\MACHINE\NETWORK.BAT

cls
REM recover previous NCFILES
IF NOT EXIST C:\%ROOT%.BAK\NCFILES\*.*  GOTO NCxSucceed
ECHO.
REM choice /c:yn /t:y,5 NC_FILES exist! ,Succeed to it
REM IF ERRORLEVEL 2 GOTO NCxSucceed
ECHO NC work files ,succeeding ...
deltree /Y C:\%ROOT%\NCFILES\*.* >NUL
IF EXIST C:\%ROOT%.BAK\NCFILES\*.*    MOVE /Y C:\%ROOT%.BAK\NCFILES\*.*  C:\%ROOT%\NCFILES\.  >NUL
deltree /Y C:\%ROOT%.BAK\NCFILES >NUL
IF EXIST C:\%ROOT%.BAK\MACRO\O9001    MOVE /Y C:\%ROOT%.BAK\MACRO\O9001   C:\%ROOT%\NCFILES\. >NUL
IF EXIST C:\%ROOT%.BAK\MACRO\O9002    MOVE /Y C:\%ROOT%.BAK\MACRO\O9002   C:\%ROOT%\NCFILES\. >NUL
IF EXIST C:\%ROOT%.BAK\MACRO\O9003    MOVE /Y C:\%ROOT%.BAK\MACRO\O9003   C:\%ROOT%\NCFILES\. >NUL

:NCxSucceed

REM === recover previous CAMPRJ ===
cls
IF NOT EXIST C:\%ROOT%.BAK\CAMPRJ\*.*  GOTO CAMxSucceed
ECHO.
ECHO CAM work files ,succeeding ...
deltree /Y C:\%ROOT%\CAMPRJ\*.* >NUL
IF EXIST C:\%ROOT%.BAK\CAMPRJ\*.DAT   MOVE /Y C:\%ROOT%.BAK\CAMPRJ\*.DAT  C:\%ROOT%\CAMPRJ\. >NUL
IF EXIST C:\%ROOT%.BAK\CAMPRJ\*.TDB   MOVE /Y C:\%ROOT%.BAK\CAMPRJ\*.TDB  C:\%ROOT%\CAMPRJ\. >NUL
IF EXIST C:\%ROOT%.BAK\CAMPRJ\*.DXF   MOVE /Y C:\%ROOT%.BAK\CAMPRJ\*.DXF  C:\%ROOT%\CAMPRJ\. >NUL
IF EXIST C:\%ROOT%.BAK\CAMPRJ\D*      MOVE /Y C:\%ROOT%.BAK\CAMPRJ\D*     C:\%ROOT%\CAMPRJ\. >NUL
deltree /Y C:\%ROOT%.BAK\CAMPRJ >NUL

:CAMxSucceed
REM === RESTORE FONTS TO CURRENT ===
IF EXIST C:\%ROOT%.BAK\FONTS\*.*      MOVE /Y C:\%ROOT%.BAK\FONTS\*.*     C:\%ROOT%\FONTS\.  >NUL
deltree /Y C:\%ROOT%.BAK\FONTS >NUL
REM=================================

cls

REM recover previous MACHINE
IF NOT EXIST C:\%ROOT%.BAK\MACHINE\param.*  GOTO MacNoSucceed
ECHO.
REM choice /c:yn /t:y,5 MACHINE_SET exist! ,Succeed to it
REM IF ERRORLEVEL 2 GOTO MacNoSucceed
IF EXIST C:\%ROOT%.BAK\MACHINE\PLCIO.CFG    COPY /Y /V C:\%ROOT%.BAK\MACHINE\PLCIO.CFG   C:\%ROOT%\MACHINE\.  >NUL
IF EXIST C:\%ROOT%.BAK\MACHINE\CNC.LAD      COPY /Y /V C:\%ROOT%.BAK\MACHINE\CNC.LAD     C:\%ROOT%\MACHINE\.  >NUL
IF EXIST C:\%ROOT%.BAK\MACHINE\CNC.PAR      COPY /Y /V C:\%ROOT%.BAK\MACHINE\CNC.PAR     C:\%ROOT%\MACHINE\.  >NUL
IF EXIST C:\%ROOT%.BAK\MACHINE\CNC.L88      COPY /Y /V C:\%ROOT%.BAK\MACHINE\CNC.L88     C:\%ROOT%\MACHINE\.  >NUL
IF EXIST C:\%ROOT%.BAK\MACHINE\CNC.SYM      COPY /Y /V C:\%ROOT%.BAK\MACHINE\CNC.SYM     C:\%ROOT%\MACHINE\.  >NUL
REM IF EXIST C:\%ROOT%.BAK\MACHINE\PARAM.TXT    COPY /Y /V C:\%ROOT%.BAK\MACHINE\PARAM.TXT   C:\%ROOT%\MACHINE\.  >NUL
IF EXIST C:\%ROOT%.BAK\MACHINE\PARAM.BIN    COPY /Y /V C:\%ROOT%.BAK\MACHINE\PARAM.BIN   C:\%ROOT%\MACHINE\.  >NUL
IF EXIST C:\%ROOT%.BAK\MACHINE\PARAM.DEF    COPY /Y /V C:\%ROOT%.BAK\MACHINE\PARAM.DEF   C:\%ROOT%\MACHINE\.  >NUL
IF EXIST C:\%ROOT%.BAK\MACHINE\SRAM         COPY /Y /V C:\%ROOT%.BAK\MACHINE\SRAM        C:\%ROOT%\MACHINE\.  >NUL
deltree /Y C:\%ROOT%\MACHINE\GLOBAL*.DAT >NUL
deltree /Y C:\%ROOT%\MACHINE\GREADY*.BIN >NUL
deltree /Y C:\%ROOT%\MACHINE\GRUNH*.BIN  >NUL
deltree /Y C:\%ROOT%\MACHINE\GRUNL*.BIN  >NUL
IF EXIST C:\%ROOT%.BAK\MACHINE\GLOBAL*.DAT  COPY /Y /V C:\%ROOT%.BAK\MACHINE\GLOBAL*.DAT C:\%ROOT%\MACHINE\.  >NUL
IF EXIST C:\%ROOT%.BAK\MACHINE\GREADY*.BIN  COPY /Y /V C:\%ROOT%.BAK\MACHINE\GREADY*.BIN C:\%ROOT%\MACHINE\.  >NUL
IF EXIST C:\%ROOT%.BAK\MACHINE\GRUNH*.BIN   COPY /Y /V C:\%ROOT%.BAK\MACHINE\GRUNH*.BIN  C:\%ROOT%\MACHINE\.  >NUL
IF EXIST C:\%ROOT%.BAK\MACHINE\GRUNL*.BIN   COPY /Y /V C:\%ROOT%.BAK\MACHINE\GRUNL*.BIN  C:\%ROOT%\MACHINE\.  >NUL
IF EXIST C:\%ROOT%.BAK\MACHINE\GRAPH.DAT    COPY /Y /V C:\%ROOT%.BAK\MACHINE\GRAPH.DAT   C:\%ROOT%\MACHINE\.  >NUL
IF EXIST C:\%ROOT%.BAK\MACHINE\CHI_MLC.ERR  COPY /Y /V C:\%ROOT%.BAK\MACHINE\CHI_MLC.ERR C:\%ROOT%\MACHINE\.  >NUL
IF EXIST C:\%ROOT%.BAK\MACHINE\ENG_MLC.ERR  COPY /Y /V C:\%ROOT%.BAK\MACHINE\ENG_MLC.ERR C:\%ROOT%\MACHINE\.  >NUL
IF EXIST C:\%ROOT%.BAK\MACHINE\USRCHI.STR   COPY /Y /V C:\%ROOT%.BAK\MACHINE\USRCHI.STR  C:\%ROOT%\MACHINE\.  >NUL
IF EXIST C:\%ROOT%.BAK\MACHINE\USRENG.STR   COPY /Y /V C:\%ROOT%.BAK\MACHINE\USRENG.STR  C:\%ROOT%\MACHINE\.  >NUL
IF EXIST C:\%ROOT%.BAK\MACHINE\*.INI        COPY /Y /V C:\%ROOT%.BAK\MACHINE\*.INI       C:\%ROOT%\MACHINE\.  >NUL
IF EXIST C:\%ROOT%.BAK\MACHINE\*.PCX        COPY /Y /V C:\%ROOT%.BAK\MACHINE\*.pcx       C:\%ROOT%\MACHINE\.  >NUL
IF EXIST C:\%ROOT%.BAK\MACHINE\BATCH.*      COPY /Y /V C:\%ROOT%.BAK\MACHINE\BATCH.*     C:\%ROOT%\MACHINE\.  >NUL
IF EXIST C:\%ROOT%.BAK\MACHINE\CNCSYS.LOG   COPY /Y /V C:\%ROOT%.BAK\MACHINE\CNCSYS.LOG  C:\%ROOT%\MACHINE\.  >NUL
IF EXIST C:\%ROOT%.BAK\MACHINE\XPNET.bat    COPY /Y /V C:\%ROOT%.BAK\MACHINE\XPNET.BAT   C:\%ROOT%\MACHINE\.  >NUL
IF EXIST C:\%ROOT%.BAK\MACHINE\NETWORK.BAT  COPY /Y /V C:\%ROOT%.BAK\MACHINE\NETWORK.BAT C:\%ROOT%\MACHINE\.  >NUL
IF EXIST C:\%ROOT%.BAK\MACHINE\AIC.BIN      COPY /Y /V C:\%ROOT%.BAK\MACHINE\AIC.BIN     C:\%ROOT%\MACHINE\.  >NUL
IF EXIST C:\%ROOT%.BAK\MACHINE\CCD*.DAT     COPY /Y /V C:\%ROOT%.BAK\MACHINE\CCD*.DAT    C:\%ROOT%\MACHINE\.  >NUL
IF EXIST C:\%ROOT%.BAK\MACHINE\UPARAM*.DAT  COPY /Y /V C:\%ROOT%.BAK\MACHINE\UPARAM*.DAT C:\%ROOT%\MACHINE\.  >NUL
IF EXIST C:\%ROOT%.BAK\MACHINE\GPARAM*.DAT  COPY /Y /V C:\%ROOT%.BAK\MACHINE\GPARAM*.DAT C:\%ROOT%\MACHINE\.  >NUL
IF EXIST C:\%ROOT%.BAK\MACHINE\GDI*.STR     COPY /Y /V C:\%ROOT%.BAK\MACHINE\GDI*.STR    C:\%ROOT%\MACHINE\.  >NUL
deltree /Y C:\%ROOT%.BAK >NUL

cls
ECHO Succeed to previous MACHINE_SETTINGS finish!

:MacNoSucceed
IF EXIST C:\%INSTDIR%\Maker\*.*    copy /y /v C:\%INSTDIR%\Maker\*.*    C:\%ROOT%\MACHINE\.  >NUL
IF EXIST C:\%INSTDIR%\Ncfiles\*.*  copy /y /v C:\%INSTDIR%\Ncfiles\*.*  C:\%ROOT%\Ncfiles\.  >NUL
IF EXIST C:\%INSTDIR%\Cam\*.*      copy /y /v C:\%INSTDIR%\Cam\*.*      C:\%ROOT%\CAMPRJ\.   >NUL
                                                                                        
REM === COPY MACHINE TO RAMDISK ===
IF "%BEXIST%"=="YES"  COPY /Y C:\%ROOT%\MACHINE\*.* B:\ >NUL

REM ===INSTALL TO LncXXXXX.B2 ================================
cls
ECHO.
ECHO Installing B2...
ECHO.
IF NOT EXIST C:\%ROOTB2%\EXIST.DIR GOTO B2NEXIST
deltree /Y C:\%ROOTB2% >NUL
:B2NEXIST

md C:\%ROOTB2%
REM === current dir: system root ===
C:
cd \%ROOTB2%
REM C:\%INSTDIR%\%EXESFX% -y  >NUL
REM IF ERRORLEVEL 1  GOTO xCNCEXE

REM IF EXIST C:\%ROOT%\exe\xpnet.bat   copy /y /v C:\%ROOT%\exe\xpnet.bat C:\%ROOTB2%\exe\.   >NUL
ECHO C:\%ROOTB2% >C:\%ROOTB2%\EXIST.DIR
REM IF EXIST C:\%ROOT%\FONTS\*.* XCOPY /S /Y C:\%ROOT%\FONTS C:\%ROOTB2%\FONTS\ >NUL
XCOPY /S /Y C:\%ROOT%\MACHINE C:\%ROOTB2%\MACHINE\ >NUL

REM ECHO SET LNCVER=%LNC_VERSION%> C:\%ROOTB2%\EXE\%INSTVERBAT%
REM ECHO SET AUTOVER=%AUTO_VERSION%>> C:\%ROOTB2%\EXE\%INSTVERBAT%

REM COPY /Y C:\%INSTDIR%\RES.BAT C:\  >NUL
REM COPY /Y C:\%INSTDIR%\RES.BAT C:\DOS\.  >NUL

C:
cd\
cls

REM === INSATLL TO 2nd CF card IF exist ================================
ECHO.
IF "%D2EXIST%"==""  GOTO CF2_NOT_EXIST

REM === copy autoexec.bat and config.sys to c disk ===
COPY /Y /V c:\CONFIG.SYS   D:\  >NUL
COPY /Y /V c:\AUTOEXEC.BAT D:\  >NUL
COPY /Y /V c:\SetRoot.BAT  D:\  >NUL

cls
ECHO.
ECHO Installing to 2nd card...
ECHO.

IF NOT EXIST D:\%ROOT%\EXIST.DIR GOTO DNEXIST
deltree /Y D:\%ROOT% >NUL
:DNEXIST

md D:\%ROOT%  >NUL
ECHO D:\%ROOT% >D:\%ROOT%\EXIST.DIR

REM === current dir: system root ===
D:
cd \%ROOT%
C:\%INSTDIR%\%EXESFX% -y >NUL
IF ERRORLEVEL 1 GOTO xCNCEXE

copy /y c:\dos\isdsk.exe d:\dos\.  >NUL
IF EXIST C:\%ROOT%\FONTS\*.* XCOPY /S /Y C:\%ROOT%\FONTS D:\%ROOT%\FONTS\ >NUL
XCOPY /S /Y C:\%ROOT%\MACHINE D:\%ROOT%\MACHINE\ >NUL

REM IF EXIST C:\%ROOT%\exe\xpnet.bat   copy /y /v C:\%ROOT%\exe\xpnet.bat D:\%ROOT%\exe\.   >NUL
ECHO SET LNCVER=%LNC_VERSION%> D:\%ROOT%\EXE\%INSTVERBAT%
ECHO SET AUTOVER=%AUTO_VERSION%>> D:\%ROOT%\EXE\%INSTVERBAT%

REM COPY /Y C:\%INSTDIR%\RES.BAT D:\ >NUL
REM COPY /Y C:\%INSTDIR%\RES.BAT D:\DOS\. >NUL

D:
cd\
cls

:CF2_NOT_EXIST

REM==========================================================
REM clear install files
REM ECHO Backup ...
REM IF EXIST C:\%ROOT%.BAK\EXIST.DIR  GOTO NOTBAKUP
REM md C:\%ROOT%.BAK
REM ECHO C:\%ROOT%.BAK >C:\%ROOT%.BAK\EXIST.DIR
REM md C:\%ROOT%.BAK\EXE
REM IF EXIST C:\%ROOT%\EXE\*.*      COPY /Y /V C:\%ROOT%\EXE\*.* C:\%ROOT%.BAK\EXE\*.*  >NUL
REM md C:\%ROOT%.BAK\MACHINE
REM IF EXIST C:\%ROOT%\MACHINE\*.*  COPY /Y /V C:\%ROOT%\MACHINE\*.* C:\%ROOT%.BAK\MACHINE\*.*  >NUL
REM md C:\%ROOT%.BAK\MACRO
REM IF EXIST C:\%ROOT%\MACRO\*.*    COPY /Y /V C:\%ROOT%\MACRO\*.* C:\%ROOT%.BAK\MACRO\*.*  >NUL
REM md C:\%ROOT%.BAK\RESOURCE
REM IF EXIST C:\%ROOT%\RESOURCE\*.* COPY /Y /V C:\%ROOT%\RESOURCE\*.* C:\%ROOT%.BAK\RESOURCE\*.*  >NUL
REM
REM :NOTBAKUP
REM SET FINISHED=YES

ECHO.
ECHO.
cls
ECHO  Wonderful ! Fully install finish!!
ECHO.

PAUSE
GOTO QUIT

REM ------------------------------------------------------------------
:xInstFailure
ECHO Install failure....
ECHO check A disk or inform your provider!
GOTO QUIT

:xCNCEXE
ECHO File '%EXESFX%' extracting failure....
ECHO check this SFX file or inform your provider!
GOTO QUIT

REM ------------------------------------------------------------------
:QUIT
REM delete install temp directory
deltree /Y C:\%INSTDIR%  >NUL

cls
ECHO System restart ,please wait....
ECHO.

:BYE
REM REBOOT
IF EXIST C:\DOS\Reset.com C:\DOS\Reset.com
ECHO Please reboot and reinstall OS-UTILITY

SET INSTSOURCEDIR=
SET INSTDIR=
SET PATH=%PRE_PATH%
SET PRE_PATH=
SET FLAG_FILE=
REM SET NOTICE_ACK=
SET SAME_FLAG=
SET INSTVERBAT=
SET LNC_VERSION=
SET LNCVER=
SET MIN_SIZE=
SET D2EXIST=
SET BEXIST=
SET FINISHED=

C:
cd\
